In [4]:
# Install nump
# https://numpy.org/doc/
# !pip install numpy

In [5]:
# Import numpy
import numpy as np

In [22]:
# Creating Numpy Array
a1 = np.array([10,20,30,40], dtype = "int16")
a1

array([10, 20, 30, 40], dtype=int16)

In [11]:
a1.dtype

dtype('int32')

In [23]:
# 2-D array
arr2 = np.array([
    [1,2,3,4],
    [10,20,30,40],
    [21,22,23,24],],dtype = "int64")
arr2

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40],
       [21, 22, 23, 24]], dtype=int64)

## Numpy Property

In [13]:
arr2.dtype

dtype('int32')

In [14]:
# Shape
print(a1.shape)
print(arr2.shape)

(4,)
(3, 4)


In [17]:
# Ndim
print(a1.ndim)
print(arr2.ndim)

1
2


In [19]:
# Size
print(a1.size)
print(arr2.size)


4
12


In [27]:
# Itemsize
a1 = np.array([10,20,30,40], dtype = "int8")
a2 = np.array([[1,2,3,4],[10,20,30,40],[21,22,23,24],],dtype = "int32")
arr2
print(a1.itemsize)
print(a2.itemsize)
print(a1.dtype)

1
4
int8


## Creat array in other ways

In [34]:
a1one = np.zeros((5,3),dtype = 'int8')
print(a1one)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [36]:
a1 = np.ones((5,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
# List
import time
start_time = time.process_time()
list1 = [ i for i in range(10000000)]
list2 = [x +2 for x in list1]
end_time = time.process_time()
print(end_time - start_time)



2.53125


In [42]:
# Numpy array
import time
start_time = time.process_time()
a1 = np.arange(10000000)
a2 = a1 + 2
end_time = time.process_time()
print(end_time - start_time)

0.046875


In [53]:
# arange
a1 =np.arange(20,51)
a1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])


# Indexing and slicing

In [57]:
marks = np.array([
    [10,20,30],
    [21,31,41],
    [50,60,70]])
marks

array([[10, 20, 30],
       [21, 31, 41],
       [50, 60, 70]])

In [58]:
print(marks.size)

9


In [62]:
print(marks[0,1])
print(marks[1,2])
print(marks[2,0])



20
41
50


In [63]:
a1 = np.arange(1,10)

In [64]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Slicing with 1-D array

In [66]:
print(a1[2:5])
print(a1[0:6])

[3 4 5]
[1 2 3 4 5 6]


# Slicing with 2-D array

In [71]:
marks

array([[10, 20, 30],
       [21, 31, 41],
       [50, 60, 70]])

In [75]:
print(marks[0:2,0:2])
marks[:,0:2]

[[10 20]
 [21 31]]


array([[10, 20],
       [21, 31],
       [50, 60]])

In [78]:
# Reshape

In [80]:
a1 = np.arange(0,12)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
a2 = a1.reshape(4,3)
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [88]:
a1.ndim

1

In [89]:
# Operation

In [91]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [92]:
a2 +2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [93]:
a2 *3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33]])

In [95]:
a1 = np.arange(0,12).reshape(4,3)
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [98]:
a2 = np.arange(20,32).reshape(4,3)
a2

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31]])

In [101]:
a3 = a1 * a2
a3

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341]])

In [102]:
a2

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31]])

In [105]:
print("a2.min:",a2.min())
print("a2.max:",a2.max())

a2.min: 20
a2.max: 31


In [107]:
a2.min(axis = 0)


array([20, 21, 22])

In [109]:
a2.min(axis = 1)

array([20, 23, 26, 29])

In [113]:
a2 = np.arange(0,12).reshape(4,3)

In [118]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [119]:
a2.max(axis = 1)

array([ 2,  5,  8, 11])

In [122]:
a2.max(axis = 0)   

array([ 9, 10, 11])

In [123]:
a2 = np.arange(0,12).reshape(4,3)

In [129]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [127]:
np.savetxt("np.txt",a2,delimiter = '|')

In [128]:
s1 = np.loadtxt("np.txt",delimiter = '|')
s1

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [132]:
a2 = np.arange(0,12).reshape(4,3)

In [143]:
a2 = np.arange(0,12).reshape(4,3)

In [140]:
a2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [144]:
a2.dtype

dtype('int32')

In [145]:
a2.dtype = np.float32

In [147]:
a2.dtype 

dtype('float32')