## NumPy
NumPy is a third-party Python library that provides support for large multidimensional arrays and matrices along with a collection of mathematical functions to operate on these elements.<br>
NumPy is a Python package that stands for ‘Numerical Python’. It is the core library for scientific computing, which contains a powerful n-dimensional array object.

**Python NumPy Array**: Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize NumPy arrays from nested Python lists and access it elements. In order to perform these NumPy operations, the next question which will come in your mind is:

In [3]:
# linspace 
import numpy as np


In [4]:
a=np.linspace(1,3,6)
print(a)

[1.  1.4 1.8 2.2 2.6 3. ]


In [5]:
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

1
3
6


In [6]:
a= np.array([(1,2,3),(3,4,5)])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [7]:
a.sum(axis=0)  # columsn wise

array([4, 6, 8])

In [8]:
a.sum(axis=1) # row wise

array([ 6, 12])

In [9]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)
print(x*y)
print(x/y)

[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]


## ravel
There is one more operation where you can convert one numpy array into a single column i.e ravel. Let me show how it is implemented practically:

In [14]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)],dtype = 'int16')
print(x.ravel())

[1 2 3 3 4 5]


In [16]:
# Getsize
x.itemsize

2

In [17]:
x.dtype

dtype('int16')

In [19]:
# Get total size
x.nbytes

12

# Accessing/Changing specific elements, rows, columns, etc

In [20]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
# Get a specific element [r, c]
a[1, 5]

13

In [22]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [24]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [26]:
a[1,5] = 99
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 99, 14]])

In [28]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 99 14]]


# 3-D Array

In [29]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
b.shape

(2, 2, 2)

In [32]:
# Get specific element (work outside in)
b[0,1,1]

4

## Initializing Different Types of Arrays

In [33]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [37]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [39]:
# Any other number (full_like)
c = np.full_like(a, 4)
c

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [40]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.21633198, 0.7163492 ],
       [0.88815779, 0.86484538],
       [0.5579491 , 0.23856708],
       [0.31333085, 0.42518027]])

In [41]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 1,  1,  6],
       [ 0, -3,  4],
       [ 7, -4,  3]])

In [1]:
# The identity matrix
np.identity(3,4)

NameError: name 'np' is not defined

In [45]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [49]:
# Be carefull while copying
a = np.array([1,2,3])
b = a
b[0] = 100

print(a)

[100   2   3]


In [50]:
a

array([100,   2,   3])