### numpy


In [105]:
import numpy as np
# !pip install numpy
# https://numpy.org/doc/stable/user/absolute_beginners.html

In [2]:
## Creating Numpy array from list

In [3]:
array1 = np.array([10,20,30,40])

In [4]:
array1

array([10, 20, 30, 40])

## Creating 1-D Array
**An array with only single row of element is called 1-D array**

In [5]:
arr1 = np.array([1,2,3,4,'mango','orange'])

In [6]:
arr1

array(['1', '2', '3', '4', 'mango', 'orange'], dtype='<U11')

## Creating 2-D array
**2D array can be created by passing nested lists to the array function**<br>
### Some attribute of numpy
**ndarray.ndim : Give the number of dimensions of the array as integer**<br>
**2D array,has two axes . the row-axis is called axis-0,column-axis is called axis-1**
**The number of axes is also called the array's rank**

In [7]:
arr2 = np.array([[1,2,3,4],[10,20,30,20],[5,2,3,9]])

In [8]:
arr2

array([[ 1,  2,  3,  4],
       [10, 20, 30, 20],
       [ 5,  2,  3,  9]])

In [9]:
arr1.ndim

1

In [10]:
arr2.ndim

2

## ndarray.shape
**It gives the sequence of integers indicating the size of the array for each dimension**

In [11]:
array1.shape

(4,)

In [12]:
arr2.shape

(3, 4)

## ndarray.size
**It gives the total number of element of the array,This is equal to the product of the element of shape**

In [13]:
arr2.size

12

## ndarray.dtype
**Data type of the elements of the array. All the element of an array are of same data type**<br>
**Common data types are int32,int64,float32,float64,U32 ,etc""


In [14]:
arr2.dtype

dtype('int32')

In [15]:
array1.dtype

dtype('int32')

In [16]:
arr1.dtype

dtype('<U11')

## ndarray.itemsize
**It specifies the size in bytes of each element of the array**<br>


In [17]:
arr1.itemsize

44

## Other way to create Data type

In [18]:
arr4 = np.array([[1,2],[3,4]], dtype = float)

In [19]:
arr4

array([[1., 2.],
       [3., 4.]])

In [20]:
arr4.dtype

dtype('float64')

# Other ways of creating Numpy array

## Zeros

In [21]:
arr5 = np.zeros((3,4))
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
a1 = np.zeros(10)
a1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Ones

In [23]:
arr6 = np.ones((5,3))
arr6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Create an Array of 2’s

In [85]:
arr6 = np.ones((5,3),dtype = 'int16') * 2
arr6

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int16)

## arange
To create an array of any length write: np.arange(size).

To create an array of size 9 write : np.arange(9).

In [24]:
arng = np.arange(0,10,2)
arng

array([0, 2, 4, 6, 8])

In [25]:
arng2 = np.arange(-2,20,1)
arng2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17, 18, 19])

# Indexing and slicing
**Numpy array can be index, sliced and iterate over it**

In [26]:
marks = np.array(
[
    [78,67,56],
    [76,75,47],
    [84,59,60],
    [67,72,54]
]
)

In [27]:
marks

array([[78, 67, 56],
       [76, 75, 47],
       [84, 59, 60],
       [67, 72, 54]])

In [28]:
marks.size

12

In [29]:
marks[0,1]

67

In [30]:
marks[3,2]

54

In [31]:
arr1 = np.array([2,3,4,10,55,6])
arr1

array([ 2,  3,  4, 10, 55,  6])

In [32]:
# arr1[2:10]
arr1[2:5]

array([ 4, 10, 55])

In [33]:
arr1[::-1]

array([ 6, 55, 10,  4,  3,  2])

In [34]:
arr1

array([ 2,  3,  4, 10, 55,  6])

In [35]:
arr1[-2:-4:-1]

array([55, 10])

# Slicing in 2D array

In [36]:
marks

array([[78, 67, 56],
       [76, 75, 47],
       [84, 59, 60],
       [67, 72, 54]])

In [37]:
# access all element in 3rd columsn

In [38]:
marks[0:4,2]

array([56, 47, 60, 54])

In [39]:
marks[1:3,0:2]

array([[76, 75],
       [84, 59]])

In [40]:
marks[:,2]

array([56, 47, 60, 54])

In [41]:
marks[1,:]

array([76, 75, 47])

In [42]:
## Operations on array

In [43]:
m1 = np.array([[1,2],[2,3]])
m2 = np.array([[4,2],[2,3]])

In [44]:
m1

array([[1, 2],
       [2, 3]])

In [45]:
m2

array([[4, 2],
       [2, 3]])

In [46]:
m3 = m1 + m2

In [47]:
m3

array([[5, 4],
       [4, 6]])

In [48]:
m4 = m1-m2
m4

array([[-3,  0],
       [ 0,  0]])

In [49]:
m5 = m1*m2

In [50]:
m5

array([[4, 4],
       [4, 9]])

In [51]:
m1**2

array([[1, 4],
       [4, 9]])

# Transpose

In [52]:
marks = np.array(
[
    [78,67,56],
    [76,75,47],
    [84,59,60],
    [67,72,54]
]
)

In [53]:
marks

array([[78, 67, 56],
       [76, 75, 47],
       [84, 59, 60],
       [67, 72, 54]])

In [54]:
marks.T

array([[78, 76, 84, 67],
       [67, 75, 59, 72],
       [56, 47, 60, 54]])

In [55]:
marks.transpose()

array([[78, 76, 84, 67],
       [67, 75, 59, 72],
       [56, 47, 60, 54]])

# sorting

In [56]:
a1 = np.array([10,20,50,2,5,66])

In [57]:
a1.sort()

In [58]:
a1

array([ 2,  5, 10, 20, 50, 66])

In [59]:
marks

array([[78, 67, 56],
       [76, 75, 47],
       [84, 59, 60],
       [67, 72, 54]])

In [60]:
marks.sort(axis = 1)

In [61]:
marks

array([[56, 67, 78],
       [47, 75, 76],
       [59, 60, 84],
       [54, 67, 72]])

In [62]:
marks.sort(axis = 0)
marks

array([[47, 60, 72],
       [54, 67, 76],
       [56, 67, 78],
       [59, 75, 84]])

## Concatenating Array
**Concatenation means joining tow or more arrays**

In [63]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[6,7],[8,9]],dtype = m1.dtype)


In [64]:
m3 = np.concatenate((m1,m2),axis=1)

In [65]:
m3

array([[1, 2, 6, 7],
       [3, 4, 8, 9]])

In [66]:
m4 = np.concatenate((m1,m2),axis=0)
m4

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [67]:
m11 = np.array([[1,2,3],[3,4,3]])

In [68]:
m12 =np.concatenate((m1,m11),axis=1)

In [69]:
m12

array([[1, 2, 1, 2, 3],
       [3, 4, 3, 4, 3]])

In [70]:
m1.shape

(2, 2)

In [71]:
m11.shape

(2, 3)

# Reshape

In [72]:
a1 = np.arange(10,22)
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [73]:
a1.reshape(2,6)

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

# Operation

In [75]:
marks = np.array([[78,67,56],[76,75,47],[84,59,60],[67,72,54]])

In [76]:
marks.min()

47

In [77]:
marks.max()

84

In [78]:
marks.sum()

795

In [79]:
marks.mean()


66.25

In [107]:
## Load Data
# save np array data
arr = np.arange(1,101).reshape(20,5)
np.savetxt('np_data.txt',arr,delimiter = "|")

In [109]:
# load Data
data = np.loadtxt('np_data.txt',delimiter = "|")
data[0]

array([1., 2., 3., 4., 5.])

In [ ]:
m1,m2,m3,m4 = np.loadtxt('numpy_load.csv',skiprows = 1,delimiter = ',',dtype = int,unpack = True)

In [99]:
a =np.ones((900000,3)) * 9
a[2:5,:]

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])