In [1]:
import numpy as np

In [2]:
d3 = [
    [[1,2,3,4],[10,20,30,40]],
    [[1,2,3,4],[10,20,30,40],],
    [[1,2,3,4],[10,20,30,40],],
    
    ]
ar = np.array(d3,dtype = "int32")
ar

array([[[ 1,  2,  3,  4],
        [10, 20, 30, 40]],

       [[ 1,  2,  3,  4],
        [10, 20, 30, 40]],

       [[ 1,  2,  3,  4],
        [10, 20, 30, 40]]])

In [5]:
ar[0,0,3]

4

In [17]:
ar.shape

(3, 2, 4)

In [22]:
# Test List
import time
list1 = [ i for i in range(10000000)]
start_time = time.process_time()
list2 = [x+2 for x in list1]
end_time = time.process_time()
print(end_time - start_time)
len(list2)

1.0


10000000

In [21]:
import time
a1 = np.arange(10000000)
start_time = time.process_time()
a2 = a1 + 2
end_time = time.process_time()
print(end_time - start_time)
len(a2)

0.015625


10000000

In [55]:
# save np array data
arr = np.arange(1,101).reshape(20,5)

In [57]:
np.savetxt('np_data.txt',arr,delimiter = "|")

In [61]:
# load Data
data = np.loadtxt('np_data.txt',delimiter = "|")


In [62]:
a = np.array([1,2,3], float)

In [63]:
a

array([1., 2., 3.])

In [68]:
data.tolist()

[[1.0, 2.0, 3.0, 4.0, 5.0],
 [6.0, 7.0, 8.0, 9.0, 10.0],
 [11.0, 12.0, 13.0, 14.0, 15.0],
 [16.0, 17.0, 18.0, 19.0, 20.0],
 [21.0, 22.0, 23.0, 24.0, 25.0],
 [26.0, 27.0, 28.0, 29.0, 30.0],
 [31.0, 32.0, 33.0, 34.0, 35.0],
 [36.0, 37.0, 38.0, 39.0, 40.0],
 [41.0, 42.0, 43.0, 44.0, 45.0],
 [46.0, 47.0, 48.0, 49.0, 50.0],
 [51.0, 52.0, 53.0, 54.0, 55.0],
 [56.0, 57.0, 58.0, 59.0, 60.0],
 [61.0, 62.0, 63.0, 64.0, 65.0],
 [66.0, 67.0, 68.0, 69.0, 70.0],
 [71.0, 72.0, 73.0, 74.0, 75.0],
 [76.0, 77.0, 78.0, 79.0, 80.0],
 [81.0, 82.0, 83.0, 84.0, 85.0],
 [86.0, 87.0, 88.0, 89.0, 90.0],
 [91.0, 92.0, 93.0, 94.0, 95.0],
 [96.0, 97.0, 98.0, 99.0, 100.0]]

In [70]:
data.fill(99)
data

array([[99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99.]])

In [80]:
a = np.array([[24,2],[3,-1],[3,5]],float)
a

array([[24.,  2.],
       [ 3., -1.],
       [ 3.,  5.]])

In [83]:
a.mean(axis = 0)

array([10.,  2.])

In [82]:
a.mean(axis = 1)

array([13.,  1.,  4.])

In [84]:
a.mean()

6.0

In [85]:
a.max()

24.0

In [86]:
a.max(axis = 0)

array([24.,  5.])

In [87]:
a.max(axis = 1)

array([24.,  3.,  5.])

In [8]:
a = np.arange(0,30).reshape(10,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [23]:
a1=np.array(np.arange(0,10)).reshape(5,2)

In [24]:
a1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
a2 = np.arange(0,10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])