In [1]:
#NUmpy 3

In [3]:
import numpy as np 


## Array Attribute
**Shape**
This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.


In [6]:
a = np.array([[1,2,3],[4,5,6]]) 
a


array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a.shape

(2, 3)

In [8]:
a.shape = (3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
a.shape

(3, 2)

# Reshape
NumPy also provides a reshape function to resize an array.

In [11]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
b = a.reshape((3,2))
b

array([[1, 2],
       [3, 4],
       [5, 6]])

## ndarray.ndim
## This array attribute returns the number of array dimensions.

In [19]:
a1 = np.arange(24) 
a2 = np.array([[1,2,3],[4,5,6]])
a3 = np.array(
[
    [
    [1,2,3],
    [4,5,6]
    ],
    [
    [10,20,30],
    [40,50,60]
    ]
    
]
)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


## numpy.itemsize
This array attribute returns the length of each element of array in bytes.

In [23]:
x = np.array([1,2,3,4,5], dtype = np.int8) 
print(x.itemsize)

1


In [24]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [25]:
# Creation of array

## Braodcasting 
The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

In [29]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
c

array([ 10,  40,  90, 160])

If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes.

In [32]:

a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
a

array([[ 0.,  0.,  0.],
       [10., 10., 10.],
       [20., 20., 20.],
       [30., 30., 30.]])

In [33]:
b

array([1., 2., 3.])

In [34]:
print(a + b)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


# terating Over Array
NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

In [36]:
a = np.arange(0,60,5)
print(a)
a = a.reshape(3,4)
print(a)

[ 0  5 10 15 20 25 30 35 40 45 50 55]
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [38]:

for x in np.nditer(a):
   print(x)

0
5
10
15
20
25
30
35
40
45
50
55
