## NumPy
NumPy is a third-party Python library that provides support for large multidimensional arrays and matrices along with a collection of mathematical functions to operate on these elements.<br>
NumPy is a Python package that stands for ‘Numerical Python’. It is the core library for scientific computing, which contains a powerful n-dimensional array object.

**Python NumPy Array**: Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize NumPy arrays from nested Python lists and access it elements. In order to perform these NumPy operations, the next question which will come in your mind is:

In [2]:
# linspace 
import numpy as np


In [8]:
a=np.linspace(1,3,6)
print(a)

[1.  1.4 1.8 2.2 2.6 3. ]


In [9]:
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

1
3
6


In [11]:
a= np.array([(1,2,3),(3,4,5)])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [13]:
a.sum(axis=0)  # columsn wise

array([4, 6, 8])

In [15]:
a.sum(axis=1) # row wise

array([ 6, 12])

In [16]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)
print(x*y)
print(x/y)

[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]


## ravel
There is one more operation where you can convert one numpy array into a single column i.e ravel. Let me show how it is implemented practically:

In [19]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]
